### ISSUE TITLE
Flow of creating Model not entirely correct

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#15]
Immediately after the POST returns, a subsequent GET should give a valid response, not a 404.

**Comment by mhmoerma** [comment]
A valid response is not returned, since a users access on a model can only be determend when the model is fully created. And when a user has no access on a model or controller, a 404 is returned. What is a possibility is that the creating user receives access to the model and set this to the model when it's actually available

**Comment by mhmoerma** [comment]
https://github.com/tengu-team/layer-sojobo/commit/d73a023caeb05be0abd8222a6881058889737c59
