### ISSUE TITLE
Does this delete all credentials? Also not a good idea .

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#36]
https://github.com/tengu-team/layer-sojobo/blob/0e338108a87bc41e1128bb03d3626d2d52c7d93f/files/sojobo_api/api/api_users.py#L211

Should refer to a specific credential when deleting it. e.g. `DELETE /users/{user}/credentials/{name}`

**Comment by gvseghbr** [comment]
Checked the code and there is no real juju action. This should definitely have an impact on the Juju controllers of a specific user. Besides this, the DELETE request relies on a message body. Although the HTTP spec does not specify if a DELETE cannot have a message body, but I don't think it's the idea behind it.

Here I would also suggest using a PUT to add and delete credentials. Or have a POST to `/users/{user}/credentials` to add a credential and a DELETE to `/users/{user}/credentials/{credential}`.

**Comment by sebastienpattyn93** [comment]
I think it's a good idea to use a POST and DELETE call on `/users/{user}/credentials` and `/users/{user}/credentials/{credential}`

**Comment by sebastienpattyn93** [comment]
The reason why this has no direct juju action is because at the moment we use the credentials to deploy a model. If a user has his credentials and has not yet deployed a model we were having issues that libjuju was not dealing with this. This is why we get the credentials out of DS when a new model is deployed and the credential tag is generated when a user deploys his first model.
