### ISSUE TITLE
What does this mean, since lowest access level on controller is always `login`

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#38]
https://github.com/tengu-team/layer-sojobo/blob/0e338108a87bc41e1128bb03d3626d2d52c7d93f/files/sojobo_api/api/api_users.py#L282

**Comment by sebastienpattyn93** [comment]
This must be a mistake, as well as issue #33 ! I think it would be a great idea to completely rewrite the whole part where users are created/ deleted or changed. The logic behind this code hasn't changed since we rewrote the api with redis integration. I think a good concept would be to use the following calls.

```
@USERS.route('/', methods=['GET'])
-> this will return all users
@USERS.route('/', methods=['POST'])
-> this will create a user on all controllers
@USERS.route('/<user>', methods=['GET'])
-> this will return a user
@USERS.route('/<user>', methods=['PUT'])
-> this will update a user password
@USERS.route('/<user>', methods=['DELETE'])
-> this will permanently delete a user on all controllers
@USERS.route('/<user>/controllers/<controller>', methods=['PUT'])
-> this will update your access on a controller
@USERS.route('/<user>/controllers/<controller>', methods=['POST'])
-> This will add a user on specific controller if the user does not already exists
@USERS.route('/<user>/controllers/<controller>', methods=['DELETE'])
-> This will delete a user on specific controller
```
If we would still want to use the enable/disable user on controller functionalities, there are 2 possibilities that we could implement
1)
```
@USERS.route('/<user>/controllers/<controller>', methods=['PUT'])
-> Where we set the access level to inactive => this will update redis, and disable a user on a ontroller
-> When granting new access again, the user will be enabled and access will be granted
```
2) Add new PUT calls to activate or deactivate user on a specific user
```
@USERS.route('/<user>/controllers/<controller>/active', methods=['PUT'])
```

**Comment by sebastienpattyn93** [comment]
@tvanhove any thoughts on this?

**Comment by sebastienpattyn93** [comment]
After looking in to the code of libjuju I noticed that there is no wrapper to remove a user at this moment. That is why we were disabling them instead of removing them

**Comment by sebastienpattyn93** [comment]
Pull request has been made to libjuju
https://github.com/juju/python-libjuju/pull/164

**Comment by sebastienpattyn93** [comment]
wrote a workaround that will work without libjuju wrapper, but wrapper is in comment for when update of libjuju is made
